### ISSUE TITLE
Sometimes, deleting a .js file or renaming .js to es6 will stop compiles for directory.

### ISSUE THREAD

**Issue by ergose** [hu9o/brackets-es6-autocompile#1]
Originally, I renamed a .js file to .es6 and then compiling stopped. I had been creating files as .es6 and had accidentally done .js, so I was correcting that when it happened. What's odd is, if it happens and then I copy all the .es6 files to a fresh directory, open that folder in brackets, and click the file, it goes back to compiling just fine. I did several variations in fresh directories, and once it stops compiling, the only thing that would work was to move them to a fresh directory. I've also tried deleting the .js file and sometimes the compiling would stop. I'd say 70% of the time one of those two things will freeze the compiler. The other 30%, deleting the file or renaming did fine and it kept working.

This may be more Brackets related, but no errors are produced until the compiles stop. Here's what I keep seeing:

```
Exception in 'currentFileChange' listener on Object {on: function, off: function, one: function, trigger: function, _EventDispatcher: true…} TypeError: Cannot read property 'fullPath' of null TypeError: Cannot read property 'fullPath' of null
    at fileChangeHandler (file:///C:/Users/ergose/AppData/Roaming/Brackets/extensions/user/vcfvct.brackets-file-format/main.js:85:56)
    at Object.trigger (/utils/EventDispatcher.js:233:40)
    at eval (/view/MainViewManager.js:1109:29)
    at Pane.trigger (/utils/EventDispatcher.js:233:40)
    at Pane._notifyCurrentViewChange (/view/Pane.js:893:14)
    at Pane._reset (/view/Pane.js:1315:18)
    at eval (/view/MainViewManager.js:1378:18)
    at eval (/thirdparty/lodash.js:26:23)
    at _t (/thirdparty/lodash.js:14:392)
    at eval (/thirdparty/lodash.js:25:369)ErrorNotification.js:125 window.console.error/utils/EventDispatcher.js:235 trigger/view/MainViewManager.js:1109 (anonymous function)/utils/EventDispatcher.js:233 trigger/view/Pane.js:893 Pane._notifyCurrentViewChange/view/Pane.js:1315 Pane._reset/view/MainViewManager.js:1378 (anonymous function)/thirdparty/lodash.js:26 (anonymous function)/thirdparty/lodash.js:14 _t/thirdparty/lodash.js:25 (anonymous function)/thirdparty/lodash.js:30 (anonymous function)/view/MainViewManager.js:492 _forEachPaneOrPanes/view/MainViewManager.js:1372 _closeAll/project/ProjectManager.js:869 _loadProject/project/ProjectManager.js:1026 (anonymous function)/filesystem/impls/appshell/AppshellFileSystem.js:187 (anonymous function)
/utils/EventDispatcher.js:236 Assertion failed:/utils/EventDispatcher.js:236 trigger/view/MainViewManager.js:1109 (anonymous function)/utils/EventDispatcher.js:233 trigger/view/Pane.js:893 Pane._notifyCurrentViewChange/view/Pane.js:1315 Pane._reset/view/MainViewManager.js:1378 (anonymous function)/thirdparty/lodash.js:26 (anonymous function)/thirdparty/lodash.js:14 _t/thirdparty/lodash.js:25 (anonymous function)/thirdparty/lodash.js:30 (anonymous function)/view/MainViewManager.js:492 _forEachPaneOrPanes/view/MainViewManager.js:1372 _closeAll/project/ProjectManager.js:869 _loadProject/project/ProjectManager.js:1026 (anonymous function)/filesystem/impls/appshell/AppshellFileSystem.js:187 (anonymous function)
ScopeManager.js:1073 Worker: Error thrown in tern_worker:undefined is not a function
TypeError: undefined is not a function
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:965:14
    at Object.SequenceExpression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:906:15)
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at propName (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:873:12)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:994:17
    at Object.AssignmentExpression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:906:15)
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at Object.walk.make.Expression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1105:7)
    at c (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:60:37)
```

This is the other variation I keep seeing (event dispatcher only has 'trigger'):

```
Exception in 'currentFileChange' listener on Object TypeError: Cannot read property 'fullPath' of null TypeError: Cannot read property 'fullPath' of null
    at fileChangeHandler (file:///C:/Users/ergose/AppData/Roaming/Brackets/extensions/user/vcfvct.brackets-file-format/main.js:85:56)
    at Object.trigger (/utils/EventDispatcher.js:233:40)
    at eval (/view/MainViewManager.js:1109:29)
    at Pane.trigger (/utils/EventDispatcher.js:233:40)
    at Pane._notifyCurrentViewChange (/view/Pane.js:893:14)
    at Pane._reset (/view/Pane.js:1315:18)
    at eval (/view/MainViewManager.js:1378:18)
    at eval (/thirdparty/lodash.js:26:23)
    at _t (/thirdparty/lodash.js:14:392)
    at eval (/thirdparty/lodash.js:25:369)
/utils/EventDispatcher.js:236 Assertion failed:/utils/EventDispatcher.js:236 trigger
extensions/default/JavaScriptCodeHints/ScopeManager.js:1073 Worker: Error thrown in tern_worker:undefined is not a function
TypeError: undefined is not a function
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:965:14
    at Object.SequenceExpression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:906:15)
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at propName (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:873:12)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:994:17
    at Object.AssignmentExpression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:906:15)
    at infer (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at Object.walk.make.Expression (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1105:7)
    at c (file:///C:/Program%20Files%20(x86)/Brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:60:37)
```

**Comment by ergose** [comment]
UPDATE: I was trying to get back to coding so I copied everything (only .es6 files + all hidden files too) to a fresh directory. Compiling didn't work. I tried again without copying my .jshintrc and .brackets.json and it started compiling. Here are my files:
**.jshintrc**

```
{
  "devel": true,
  "strict": "global"
}
```

**.brackets.json**

```
{
  "language": {
    "javascript": {
      "linting.prefer": "JSHint",
      "linting.usePreferredOnly": true
    }
  }
}
```

I have a feeling it has more to do with the ".", but j.i.c., there ya go.
